name: Docker Image CI  

on:  
  push:  
    branches: [ main ]  

env:
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/os-checker:latest
  IMAGE_TAR: /tmp/os-checker.tar

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
    - uses: actions/checkout@v4  
      
    # - name: Build the Docker image  
    #   run: |
    #     docker build -t rust-hi . 
    #     docker run rust-hi

    # Create and boot a builder using by default the docker-container driver.
    # This is not required but recommended using it to be able to build multi-platform images, export cache, etc.
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ env.IMAGE }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        outputs: type=docker,dest=${{ env.IMAGE_TAR }}

    - name: Load and Run Docker image
      run: |
        docker load --input ${{ env.IMAGE_TAR }}
        docker image ls -a
        # DEBUG means compiling os-checker from source
        # docker run -e DEBUG=1 -v ${{ github.workspace }}:/check ${{ env.IMAGE }}
        docker run -e DEBUG=1 ${{ env.IMAGE }}

    - name: Display the result of os-checker 
      run: |
        echo $PWD && ls -alh && cat summary.txt >> $GITHUB_STEP_SUMMARY
