name: Docker Image CI  

on:  
  push:  
    branches: [ main ]  

jobs:  

  build:  
    runs-on: ubuntu-latest  

    steps:  
    - uses: actions/checkout@v4  
      
    # - name: Build the Docker image  
    #   run: |
    #     docker build -t rust-hi . 
    #     docker run rust-hi

    # Create and boot a builder using by default the docker-container driver.
    # This is not required but recommended using it to be able to build multi-platform images, export cache, etc.
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/os-checker:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Fetch and Install os-checker CLI
      run: |
        curl -s https://api.github.com/repos/os-checker/os-checker/releases/latest |
          grep browser_download_url |
          grep os-checker-installer.sh |
          cut -d '"' -f 4 |
          wget -qi -
        echo 'os-checker-installer.sh is downloaded'
        sh os-checker-installer.sh
        os-checker --help
